export const GET_STREAM_INFO_REQUEST = 'GET_STREAM_INFO_REQUEST';
export const GET_STREAM_INFO_SUCCESS = 'GET_STREAM_INFO_SUCCESS';
export const GET_STREAM_INFO_FAILURE = 'GET_STREAM_INFO_FAILURE';

export const GET_STREAM_INFO = [GET_STREAM_INFO_REQUEST,  GET_STREAM_INFO_SUCCESS, GET_STREAM_INFO_FAILURE];

export const RESET_STREAM_INFO = 'RESET_STREAM_INFO';
export const FETCH_STREAM = 'FETCH_STREAM';