export const LOAD_STREAMS_REQUEST = 'LOAD_STREAMS_REQUEST';
export const LOAD_STREAMS_SUCCESS = 'LOAD_STREAMS_SUCCESS';
export const LOAD_STREAMS_FAILURE = 'LOAD_STREAMS_FAILURE';

export const LOAD_STREAMS = [LOAD_STREAMS_REQUEST,  LOAD_STREAMS_SUCCESS, LOAD_STREAMS_FAILURE];

export const ADD_STREAM_REQUEST = 'ADD_STREAM_REQUEST';
export const ADD_STREAM_SUCCESS = 'ADD_STREAM_SUCCESS';
export const ADD_STREAM_FAILURE = 'ADD_STREAM_FAILURE';

export const ADD_STREAM = [ADD_STREAM_REQUEST,  ADD_STREAM_SUCCESS, ADD_STREAM_FAILURE];

export const REMOVE_STREAM_REQUEST = 'REMOVE_STREAM_REQUEST';
export const REMOVE_STREAM_SUCCESS = 'REMOVE_STREAM_SUCCESS';
export const REMOVE_STREAM_FAILURE = 'REMOVE_STREAM_FAILURE';

export const REMOVE_STREAM = [REMOVE_STREAM_REQUEST,  REMOVE_STREAM_SUCCESS, REMOVE_STREAM_FAILURE];